services:
  app:
    container_name: gol-react-app-lynx
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
    tty: true

volumes:
  node_modules:
