services:
  app:
    container_name: gol-react-app-lynx
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /workspace/app
    volumes:
      - .:/workspace
      - node_modules:/workspace/app/node_modules
    environment:
      TZ: Asia/Tokyo
    tty: true
    network_mode: host

volumes:
  node_modules:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/app/node_modules
      o: bind
